# Generated by Django 3.0.5 on 2022-12-08 20:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='secinquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquirys_name', models.CharField(max_length=20)),
                ('inquirys_email', models.CharField(max_length=30)),
                ('inquirys_text', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'TB_inquiry',
            },
        ),
        migrations.CreateModel(
            name='ThSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'TH_SALE',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_phone', models.CharField(max_length=40, verbose_name='유저 전화번호')),
                ('user_addr', models.CharField(max_length=40, verbose_name='유저 주소')),
                ('user_level', models.CharField(max_length=8, verbose_name='등급')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'TB_USER',
            },
        ),
        migrations.CreateModel(
            name='ThSaleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_type_cd', models.CharField(max_length=10)),
                ('sale_gds', models.CharField(max_length=100)),
                ('sale_price', models.IntegerField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ThSale')),
            ],
            options={
                'db_table': 'TH_SALED',
            },
        ),
    ]
